"""Tests for scripts/research_index.py (assignment ops_reindex)."""

import importlib.util
import os
import re
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPT = os.path.join(ROOT, "scripts", "research_index.py")
INDEX_MD = os.path.join(ROOT, "docs", "RESEARCH_INDEX.md")

ALLOWED_FAMILIES = {
    "dip ladder",
    "book",
    "sleeve",
    "MANUAL",
    "execution",
    "ops",
    "diagnostic",
    "engine version",
}


def load_module():
    spec = importlib.util.spec_from_file_location("research_index", SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_collect_covers_required_sources():
    mod = load_module()
    rels = mod.collect(ROOT)
    assert len(rels) > 200, f"expected 200+ indexed files, got {len(rels)}"
    assert len(rels) == len(set(rels)), "collect() must de-duplicate"
    assert any(r.startswith("research/tournament/") and r.endswith("/REPORT.md") for r in rels)
    assert any(r.startswith("research/diagnostics/") and r.endswith("/REPORT.md") for r in rels)
    assert any(r.endswith("result_manifest.json") for r in rels)
    for r in rels:
        assert os.path.isfile(os.path.join(ROOT, r.replace("/", os.sep))), r


def test_verdict_md_variants():
    mod = load_module()
    v = mod.extract_verdict_md("# Title\n\n## Verdict\nPROMISING as assigned: x beats y.\nMore detail.\n")
    assert v.startswith("PROMISING as assigned")
    v = mod.extract_verdict_md("## One-line verdict\n\nNOT PROMISING for any variant.\n")
    assert v.startswith("NOT PROMISING")
    v = mod.extract_verdict_md("Some text\nVERDICT: NOT PROMISING - vol thing rejected.\n")
    assert "NOT PROMISING" in v
    v = mod.extract_verdict_md("# oc_bookmodel_impl - impl only\n\nNo verdict here.\n")
    assert v and "\n" not in v


def test_verdict_manifest():
    mod = load_module()
    v = mod.extract_verdict_manifest({"status": "accepted", "audit": {"passed": True}, "note": "5.17 %/month, no losing year"})
    assert "status=accepted" in v and "audit=PASS" in v and "5.17" in v
    v = mod.extract_verdict_manifest({"status": "rejected", "audit": {"passed": True}, "result": {"note": "rejected: worse DD"}})
    assert "status=rejected" in v and "rejected" in v
    v = mod.extract_verdict_manifest({"status": "audited", "audit": {}, "result": {"selected": "G2_b26"}})
    assert "status=audited" in v


def test_family_tags_valid_and_manifest_is_engine_version():
    mod = load_module()
    assert mod.infer_family("research/parallel/rounds/parallel-20260906-r2/v301/result_manifest.json") == "engine version"
    assert mod.infer_family("research/tournament/oc_manual3/REPORT.md", "") == "MANUAL"
    assert mod.infer_family("research/diagnostics/ops_enginespeed/REPORT.md", "") == "ops"
    assert mod.infer_family("research/tournament/oc_bookcorr/REPORT.md", "") == "book"
    assert mod.infer_family("research/tournament/oc_dipexit/REPORT.md", "") == "dip ladder"
    rows = mod.build_rows(ROOT)
    fams = {r["family"] for r in rows}
    assert fams <= ALLOWED_FAMILIES, fams - ALLOWED_FAMILIES
    assert "engine version" in fams and "book" in fams


def test_build_rows_sorted_single_line_fast():
    mod = load_module()
    t0 = time.time()
    rows = mod.build_rows(ROOT)
    elapsed = time.time() - t0
    assert elapsed < 10, f"build_rows took {elapsed:.1f}s, must be < 10s"
    keys = [(r["family"], r["mtime"], r["path"]) for r in rows]
    assert keys == sorted(keys), "rows must be sorted by (family, mtime, path)"
    for r in rows:
        assert re.fullmatch(r"\d{4}-\d{2}-\d{2}", r["date"]), r
        assert "\n" not in r["verdict"] and "\r" not in r["verdict"]
        assert "|" not in r["verdict"].replace("\\|", ""), r["path"]
        assert r["verdict"], r["path"]


def test_render_deterministic_and_index_matches(tmp_path):
    mod = load_module()
    rows = mod.build_rows(ROOT)
    first = mod.render(rows)
    second = mod.render(mod.build_rows(ROOT))
    assert first == second, "render must be deterministic"
    out = tmp_path / "RESEARCH_INDEX.md"
    out.write_text(first, encoding="utf-8")
    assert out.read_text(encoding="utf-8") == first
    assert os.path.isfile(INDEX_MD), "docs/RESEARCH_INDEX.md must exist (generated by the script)"
    disk = open(INDEX_MD, encoding="utf-8").read()
    assert disk.splitlines()[0].strip() == "# Research index"
    assert "| Family | Folder | File | Date | Verdict |" in disk
    # row count on disk matches a fresh scan
    disk_rows = [ln for ln in disk.splitlines() if ln.startswith("| ")][1:]
    assert len(disk_rows) == len(rows), f"disk={len(disk_rows)} scan={len(rows)}"
