#!/bin/bash
# Wait until a worker's detached background jobs have finished, then dispatch its continuation session.
# Saves RAM: an idle OpenCode session that only polls a log still holds ~1-1.5 GB, so a worker whose session died while its
# jobs keep running is re-dispatched only when the jobs are done.
#
# usage: scripts/opencode_after_jobs.sh <cmdline wildcard> <tag> <ASSIGNMENT.md> [extra message]
#   the PowerShell -like wildcard is matched against python.exe command lines (e.g. '*oc_kronosfeat*compute_*'; no backslashes);
#   POLL_S=120 between checks. A failed process query counts as 'still running' (never dispatches on an error).
# Do not edit this file while an instance runs (bash reads scripts incrementally).
set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
PAT="$1"; shift
POLL_S="${POLL_S:-120}"
alive() {
  powershell -NoProfile -Command "@(Get-CimInstance Win32_Process -Filter \"Name='python.exe'\" -ErrorAction Stop | Where-Object { \$_.CommandLine -like '$PAT' }).Count" 2>/dev/null | tr -d '\r'
}
# only an exact "0" means finished; an error or empty output keeps waiting
while [ "$(alive)" != "0" ]; do sleep "$POLL_S"; done
echo "[after_jobs] $(date -u +%H:%M:%S) jobs matching '$PAT' finished; dispatching $1"
bash scripts/opencode_dispatch_retry.sh "$@"
